package tech.catheu.jeamlit.core;

/**
 * Exception thrown when two widgets have the same automatically generated or explicit key.
 * This mimics Streamlit's DuplicateWidgetID error behavior.
 */
public class DuplicateWidgetIDException extends RuntimeException {
    
    public DuplicateWidgetIDException(String message) {
        super(message);
    }
    
    public static DuplicateWidgetIDException forAutoGeneratedKey(String componentType, String key) {
        return new DuplicateWidgetIDException(
            String.format("There are multiple identical %s widgets with the same auto-generated key='%s'. " +
                         "To fix this, please pass a unique key argument to each widget.",
                         componentType, key)
        );
    }
    
    public static DuplicateWidgetIDException forExplicitKey(String componentType, String key) {
        return new DuplicateWidgetIDException(
            String.format("There are multiple %s widgets with the same explicit key='%s'. " +
                         "Widget keys must be unique.",
                         componentType, key)
        );
    }
}